define({
    "agent": {
        "0": {
            "ublucorea": 1,
            "ugrycorea": 2,
            "uprpcorea": 3,
            "uredcorea": 4,
            "utrqcorea": 5,
            "ublucoreb": 6,
            "ugrycoreb": 7,
            "uprpcoreb": 8,
            "uredcoreb": 9,
            "utrqcoreb": 10,
            "ublucorec": 11,
            "ugrycorec": 12,
            "uprpcorec": 13,
            "uredcorec": 14,
            "utrqcorec": 15,
            "ublurarez": 16,
            "ugryrarez": 17,
            "uprprarez": 18,
            "uredrarez": 19,
            "utrqrarez": 20,
            "ublualpha": 21,
            "ugryalpha": 22,
            "uprpalpha": 23,
            "uredalpha": 24,
            "utrqalpha": 25,
            "ubluomega": 24,
            "ugryomega": 23,
            "uprpomega": 22,
            "uredomega": 21,
            "utrqomega": 20,
        },
        "1": {
            "blucorea": 1,
            "grycorea": 2,
            "prpcorea": 3,
            "redcorea": 4,
            "trqcorea": 5,
            "blucoreb": 6,
            "grycoreb": 7,
            "prpcoreb": 8,
            "redcoreb": 9,
            "trqcoreb": 10,
            "blucorec": 11,
            "grycorec": 12,
            "prpcorec": 13,
            "redcorec": 14,
            "trqcorec": 15,
            "blurarez": 16,
            "gryrarez": 17,
            "prprarez": 18,
            "redrarez": 19,
            "trqrarez": 20,
            "blualpha": 21,
            "gryalpha": 22,
            "prpalpha": 23,
            "redalpha": 24,
            "trqalpha": 25,
            "bluomega": 26,
            "gryomega": 27,
            "prpomega": 28,
            "redomega": 29,
            "trqomega": 30,
        },
        "2": [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 35, 34, 36, 33, 37, 32, 38, 34, 36],
        "3": ["Will Bauer", "Emma Thee", "Abby Thee", "Chance Wristaker", "Yuri Flex", "Takeo Na'Chepp", "Vic Tamtoro-Egho", "Guilden Sha'mei", "Vinny Gents", "Nadia Dez a'Rei", "Bob Zest", "Faye de Carma", "Igor Blitzschaf", "Betsy Mystic", "Zen Spired", "Precious Hope", "Sveltella Daeshun", "Great Phil", "Marjorie Gretz", "Claire Patience", "Cami Kindbud", "Tristan Faith", "Annie Grrr", "Private Fear", "Torrence de Spare", "Mona Ledge", "Maya Joyce", "General Fear", "Rye Zup", "Serena Tae"],
    }
});
